EGSnrc C++ class library: EGS_ParallelBeam Class Reference
EGS_ParallelBeam Class Reference
Particle sources
A parallel beam.
#include <egs_parallel_beam.h>
Public Member Functions
EGS_ParallelBeam (int Q, EGS_BaseSpectrum *Spec, EGS_BaseShape *Shape, const string &Name="", EGS_ObjectFactory *f=0)
Constructor.
EGS_ParallelBeam (EGS_Input *, EGS_ObjectFactory *f=0)
Constructor.
void getPositionDirection (EGS_RandomGenerator *rndm, EGS_Vector &x, EGS_Vector &u, EGS_Float &wt)
EGS_Float getFluence () const
bool storeFluenceState (ostream &) const
bool setFluenceState (istream &)
bool isValid () const
Protected Member Functions
void setUp ()
Protected Attributes
EGS_BaseShape * shape
The shape.
EGS_Vector uo
The direction of the particles.
Detailed Description
A parallel beam.
A parallel beam is a source that delivers particles all having the same direction with a position within any shape. Although planar shapes would make more sense for a parallel beam, due to the abstract nature of shapes, any shape can be used. A parallel beam is defined as follows:
:start source:
    library = egs_parallel_beam
    name = some_name
    :start shape:
        definition of the shape
    :stop shape:
    :start spectrum:
        definition of the spectrum
    :stop spectrum:
    direction = Ux Uy Uz
    charge = -1 or 0 or 1 for electrons or photons or positrons
:stop source:
It is worth noting that the functionality of sources 0, 2, 10 and 13 from the RZ series of user codes and sources 0 and 1 in DOSXYZnrc can be reproduced with the parallel beam source from the EGSnrc C++ class library.
Definition at line 99 of file egs_parallel_beam.h.
Constructor & Destructor Documentation
EGS_ParallelBeam::EGS_ParallelBeam (int Q, EGS_BaseSpectrum * Spec, EGS_BaseShape * Shape, const string & Name = "", EGS_ObjectFactory * f = 0)
Constructor.
Construct a parallel beam with charge Q and spectrum Spec from a shape Shape
Definition at line 109 of file egs_parallel_beam.h.
EGS_ParallelBeam::EGS_ParallelBeam (EGS_Input * input, EGS_ObjectFactory * f = 0)
Constructor.
Construct a parallel beam from the information pointed to by inp.
Definition at line 40 of file egs_parallel_beam.cpp.
References EGS_BaseShape::createShape(), egsWarning, EGS_Input::getInput(), EGS_BaseShape::getShape(), shape, EGS_Input::takeInputItem(), uo, EGS_Vector::x, EGS_Vector::y, and EGS_Vector::z.
The documentation for this class was generated from the following files:
/home/ftessier/EGSnrc/HEN_HOUSE/egs++/sources/egs_parallel_beam/egs_parallel_beam.h
/home/ftessier/EGSnrc/HEN_HOUSE/egs++/sources/egs_parallel_beam/egs_parallel_beam.cpp