EGSnrc C++ class library: EGS_IsotropicSource Class Reference
EGS_IsotropicSource Class Reference
Particle sources
An isotropic source.
#include <egs_isotropic_source.h>
Public Types
enum GeometryConfinement { IncludeAll = 0, ExcludeAll = 1, IncludeSelected = 2, ExcludeSelected = 3 }
Geometry confinement options.
Public Member Functions
EGS_IsotropicSource (int Q, EGS_BaseSpectrum *Spec, EGS_BaseShape *Shape, EGS_BaseGeometry *geometry, const string &Name="", EGS_ObjectFactory *f=0)
Constructor.
EGS_IsotropicSource (EGS_Input *, EGS_ObjectFactory *f=0)
Constructor.
void getPositionDirection (EGS_RandomGenerator *rndm, EGS_Vector &x, EGS_Vector &u, EGS_Float &wt)
EGS_Float getFluence () const
bool storeFluenceState (ostream &) const
bool setFluenceState (istream &)
bool isValid () const
Protected Member Functions
void setUp ()
Protected Attributes
EGS_BaseShape * shape
The shape from which particles are emitted.
EGS_BaseGeometry * geom
int * regions
EGS_Float min_theta
EGS_Float max_theta
EGS_Float buf_1
EGS_Float buf_2
EGS_Float min_phi
avoid multi-calculating cos(min_theta) and cos(max_theta)
EGS_Float max_phi
int nrs
GeometryConfinement gc
Detailed Description
An isotropic source.
An isotropic source is a source that delivers particles with directions uniformly distributed in emitted from any shape. It is defined using the following input
:start source:
    library = egs_isotropic_source
    name = some_name
    :start shape:
        definition of the shape
    :stop shape:
    :start spectrum:
        definition of the spectrum
    :stop spectrum:
    charge = -1 or 0 or 1 for electrons or photons or positrons
    min theta = 80  (degree)
    max theta = 100 (degree)
:stop source:
It is worth noting that the functionality of source 3 in the RZ series of user codes or source 6 in DOSXYZnrc can be reproduced with the isotropic source from the EGSnrc C++ class library.
Definition at line 97 of file egs_isotropic_source.h.
Constructor & Destructor Documentation
EGS_IsotropicSource::EGS_IsotropicSource (int Q, EGS_BaseSpectrum * Spec, EGS_BaseShape * Shape, EGS_BaseGeometry * geometry, const string & Name = "", EGS_ObjectFactory * f = 0)
Constructor.
Construct an isotropic source with charge Q, spectrum Spec and emitting particles from the shape Shape
Definition at line 115 of file egs_isotropic_source.h.
EGS_IsotropicSource::EGS_IsotropicSource (EGS_Input * input, EGS_ObjectFactory * f = 0)
Constructor.
Construct an isotropic source from the information pointed to by inp.
Definition at line 41 of file egs_isotropic_source.cpp.
References EGS_BaseShape::createShape(), egsWarning, EGS_BaseGeometry::getGeometry(), EGS_Input::getInput(), EGS_BaseShape::getShape(), min_phi, shape, and EGS_Input::takeInputItem().
The documentation for this class was generated from the following files:
/home/ftessier/EGSnrc/HEN_HOUSE/egs++/sources/egs_isotropic_source/egs_isotropic_source.h
/home/ftessier/EGSnrc/HEN_HOUSE/egs++/sources/egs_isotropic_source/egs_isotropic_source.cpp