EGSnrc C++ class library: EGS_SourceCollection Class Reference
EGS_SourceCollection Class Reference
Particle sources
A source collection.
#include <egs_source_collection.h>
Public Member Functions
EGS_SourceCollection (const vector< EGS_BaseSource * > &S, const vector< EGS_Float > &prob, const string &Name="", EGS_ObjectFactory *f=0)
Constructor.
EGS_SourceCollection (EGS_Input *, EGS_ObjectFactory *f=0)
Constructor.
EGS_I64 getNextParticle (EGS_RandomGenerator *rndm, int &q, int &latch, EGS_Float &E, EGS_Float &wt, EGS_Vector &x, EGS_Vector &u)
EGS_Float getEmax () const
EGS_Float getFluence () const
bool storeState (ostream &data) const
bool setState (istream &data)
void resetCounter ()
virtual bool addState (istream &data_in)
bool isValid () const
Protected Member Functions
void setUp (const vector< EGS_BaseSource * > &S, const vector< EGS_Float > &)
Protected Attributes
int nsource
EGS_BaseSource ** sources
The sources in the collection.
EGS_AliasTable * table
Alias table for randomly picking a source.
EGS_I64 * last_cases
Last case returned from each source.
EGS_Float * p
The probabilities.
EGS_Float Emax
Maximum energy (max of s[j]->getEmax()).
EGS_I64 count
Independent particles delivered.
Detailed Description
A source collection.
A source collection consists of an arbitrary number of any other sources with weights of and delivers particles from with probability . A source collection is defined using
:start source:
    library = egs_source_collection
    name = some_name
    source names = list of names of previously defined sources
    weights = list of weights for the sources
:stop source:
Definition at line 83 of file egs_source_collection.h.
Constructor & Destructor Documentation
EGS_SourceCollection::EGS_SourceCollection (const vector< EGS_BaseSource * > & S, const vector< EGS_Float > & prob, const string & Name = "", EGS_ObjectFactory * f = 0)
Constructor.
Construct a source collection from the sources S using the probabilities prob.
Definition at line 93 of file egs_source_collection.h.
EGS_SourceCollection::EGS_SourceCollection (EGS_Input * input, EGS_ObjectFactory * f = 0)
Constructor.
Construct a source collection from the input pointed to by inp.
Definition at line 40 of file egs_source_collection.cpp.
References EGS_BaseSource::createSource(), egsInformation, egsWarning, EGS_Input::getInput(), EGS_BaseSource::getSource(), EGS_Input::print(), and EGS_Input::takeInputItem().
The documentation for this class was generated from the following files:
/home/ftessier/EGSnrc/HEN_HOUSE/egs++/sources/egs_source_collection/egs_source_collection.h
/home/ftessier/EGSnrc/HEN_HOUSE/egs++/sources/egs_source_collection/egs_source_collection.cpp