EGSnrc C++ class library: EGS_CylinderShape Class Reference
EGS_CylinderShape Class Reference
Shapes | Surface Shapes | Main library
A cylinder shape.
#include <egs_shapes.h>
Public Member Functions
EGS_CylinderShape (const string &Name="", EGS_ObjectFactory *f=0)
EGS_CylinderShape (EGS_Float r, EGS_Float H, const EGS_Vector &Xo=EGS_Vector(0, 0, 0), const EGS_Vector &A=EGS_Vector(0, 0, 1), const string &Name="", EGS_ObjectFactory *f=0)
EGS_CylinderShape (EGS_Float r, EGS_Float H, const EGS_AffineTransform *t, const string &Name="", EGS_ObjectFactory *f=0)
~EGS_CylinderShape ()
void setPhiRange (EGS_Float Phi_min, EGS_Float Phi_max)
EGS_Vector getPoint (EGS_RandomGenerator *rndm)
Samples and returns a point uniformly distributed within the cylinder.
EGS_Object * createObject (EGS_Input *)
EGS_Float getRadius () const
EGS_Float getHeight () const
bool supportsDirectionMethod () const
Returns true. (It is easy to implement the getPointSourceDirection() method for a cylinder.)
void getPointSourceDirection (const EGS_Vector &Xo, EGS_RandomGenerator *rndm, EGS_Vector &u, EGS_Float &wt)
Sets the direction u by picking a random point uniformly on the cylinder surface.
EGS_Float area () const
Returns the cylinder surface area.
Protected Member Functions
void getPointInCircle (EGS_RandomGenerator *rndm, EGS_Float &x, EGS_Float &y)
Get a point uniformly distributed within a circle.
Protected Attributes
EGS_Float R
Cylinder radius.
EGS_Float h
Cylinder height.
EGS_Vector xo
midpoint
EGS_Vector a
Cylinder axis.
EGS_Float phi_min
EGS_Float phi_max
bool has_phi
True, if azimuthal range restricted.
Detailed Description
A cylinder shape.
Samples random points within a cylinder or on the cylinder surfcace. Specified in the input file via
:start shape:
    type = cylinder
    radius = the cylinder radius
    height = the cylinder height
    midpoint = Ox, Oy, Oz (optional)
    axis = ax, ay, az (optional)
:stop shape:
If the optional midpoint and axis inputs are missing, the cylinder is centered about the origin and has its axis along the z-axis.
Definition at line 596 of file egs_shapes.h.
Constructor & Destructor Documentation
EGS_CylinderShape::EGS_CylinderShape (const string & Name = "", EGS_ObjectFactory * f = 0)
Construct a cylinder shape with unit radius and height centered about the origin with an axis along the z-axis.
Definition at line 635 of file egs_shapes.h.
EGS_CylinderShape::EGS_CylinderShape (EGS_Float r, EGS_Float H, const EGS_AffineTransform * t, const string & Name = "", EGS_ObjectFactory * f = 0)
Construct a cylinder shape with radius r and height H centered about the origin with axis along the z-axis.
Definition at line 655 of file egs_shapes.h.
EGS_CylinderShape::~EGS_CylinderShape ()
Destructor. Does nothing.
Definition at line 665 of file egs_shapes.h.
Member Function Documentation
void EGS_CylinderShape::setPhiRange (EGS_Float Phi_min, EGS_Float Phi_max)
Set a restriction on the azimuthal angular range
Definition at line 668 of file egs_shapes.h.
Referenced by createObject().
EGS_Object * EGS_CylinderShape::createObject (EGS_Input * input) [virtual]
Creates and returns a pointer to a cylinder shape from the information pointed to by inp, or null if the information is insufficient.
Reimplemented from EGS_Object.
Definition at line 154 of file egs_shapes.cpp.
References egsWarning, EGS_Input::getInput(), EGS_AffineTransform::getTransformation(), EGS_Object::setName(), and setPhiRange().
EGS_Float EGS_CylinderShape::getRadius () const
Get the cylinder radius
Definition at line 701 of file egs_shapes.h.
EGS_Float EGS_CylinderShape::getHeight () const
Get the cylinder height
Definition at line 705 of file egs_shapes.h.
void EGS_CylinderShape::getPointSourceDirection (const EGS_Vector & Xo, EGS_RandomGenerator * rndm, EGS_Vector & u, EGS_Float & wt) [virtual]
Sets the direction u by picking a random point uniformly on the cylinder surface.
See also:
EGS_BaseShape::getPointSourceDirection()
Reimplemented from EGS_BaseShape.
Definition at line 720 of file egs_shapes.h.
References EGS_BaseShape::area(), EGS_RandomGenerator::getAzimuth(), EGS_RandomGenerator::getUniform(), EGS_Vector::x, EGS_Vector::y, and EGS_Vector::z.
The documentation for this class was generated from the following files:
/home/ftessier/EGSnrc/HEN_HOUSE/egs++/egs_shapes.h
/home/ftessier/EGSnrc/HEN_HOUSE/egs++/egs_shapes.cpp